on: 
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environmet'    
        required: true
        default: 'warning'
      SnowNumber:
        description: 'SnowNumber'    
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 