on: 
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environmet'    
        required: true
        default: 'warning'
      SnowNumber:
        description: 'SnowNumber'    
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.Environment}}"
        echo "Tags: ${{ github.event.inputs.SnowNumber}}"
