on: 
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environmet'    
        required: true
        default: 'warning'
      SnowNumber:
        description: 'SnowNumber'    
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.Environment}}"
        echo "Tags: ${{ github.event.inputs.SnowNumber}}"

  test:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: sfdx-actions/setup-sfdx@v1
      - name: sfdx-test-run
        run: sfdx force:apex:test:run -l RunLocalTests -w 30 -u gpanja
